### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by userkilled** [WaxMoon/MultiApp#18]
How about being able to add apps to the home screen in the launcher. So that it would be easier to cut them off?
 With space numbers inside.

**Comment by userkilled** [comment]
And in general it's nice to see that it doesn't go down, I mean the app.
Thank you very much.

**Comment by WaxMoon** [comment]
You can download from Google play. It is also free to enjoy. https://play.google.com/store/apps/details?id=com.waxmoon.ma.gp @userkilled

**Comment by userkilled** [comment]
I use fdroid version. Thanks.

**Comment by userkilled** [comment]
This is really cool.

**Comment by e-t-l** [comment]
Is there any difference between the fdroid, github, and Google play versions of the apk?

I have the github release version (v1.0.6) and I do not see any way to add a homescreen shortcut for a cloned app (I believe this is what the original commenter here was asking for). I would also like this ability.

For example, my home screen launcher could have three Facebook icons next to each other; each one would open to a different profile, because they are all clones from Waxmoon. Is this possible?

**Comment by WaxMoon** [comment]
Github version is only demo for android developer. Fdroid version is same as github version.
If you want to add shortcut on home launcher, You can download from GP. GP version is also free to enjoy!
